if (( ${+commands[kubectl]} )); then
  function kubectl_alias() {
    printf '=> kubectl'
    [[ $# -gt 0 ]] && printf ' %q' "$@"
    printf '\n'
    kubectl "$@"
  }

  # Extra aliases
  alias kcgp=kgpo

  # Copyright 2019 Google Inc.
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     https://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  # Print expanded command before running it

  alias kc='kubectl_alias'
  alias kcsys='kubectl_alias --namespace=kube-system'
  alias kca='kubectl_alias apply --recursive -f'
  alias kcsysa='kubectl_alias --namespace=kube-system apply --recursive -f'
  alias kcex='kubectl_alias exec -i -t'
  alias kcsysex='kubectl_alias --namespace=kube-system exec -i -t'
  alias kclo='kubectl_alias logs -f'
  alias kcsyslo='kubectl_alias --namespace=kube-system logs -f'
  alias kclop='kubectl_alias logs -f -p'
  alias kcsyslop='kubectl_alias --namespace=kube-system logs -f -p'
  alias kcp='kubectl_alias proxy'
  alias kcg='kubectl_alias get'
  alias kcsysg='kubectl_alias --namespace=kube-system get'
  alias kcd='kubectl_alias describe'
  alias kcsysd='kubectl_alias --namespace=kube-system describe'
  alias kcrm='kubectl_alias delete'
  alias kcsysrm='kubectl_alias --namespace=kube-system delete'
  alias kcrun='kubectl_alias run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
  alias kcsysrun='kubectl_alias --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
  alias kcgpo='kubectl_alias get pods'
  alias kcsysgpo='kubectl_alias --namespace=kube-system get pods'
  alias kcdpo='kubectl_alias describe pods'
  alias kcsysdpo='kubectl_alias --namespace=kube-system describe pods'
  alias kcrmpo='kubectl_alias delete pods'
  alias kcsysrmpo='kubectl_alias --namespace=kube-system delete pods'
  alias kcgdep='kubectl_alias get deployment'
  alias kcsysgdep='kubectl_alias --namespace=kube-system get deployment'
  alias kcddep='kubectl_alias describe deployment'
  alias kcsysddep='kubectl_alias --namespace=kube-system describe deployment'
  alias kcrmdep='kubectl_alias delete deployment'
  alias kcsysrmdep='kubectl_alias --namespace=kube-system delete deployment'
  alias kcgsvc='kubectl_alias get service'
  alias kcsysgsvc='kubectl_alias --namespace=kube-system get service'
  alias kcdsvc='kubectl_alias describe service'
  alias kcsysdsvc='kubectl_alias --namespace=kube-system describe service'
  alias kcrmsvc='kubectl_alias delete service'
  alias kcsysrmsvc='kubectl_alias --namespace=kube-system delete service'
  alias kcging='kubectl_alias get ingress'
  alias kcsysging='kubectl_alias --namespace=kube-system get ingress'
  alias kcding='kubectl_alias describe ingress'
  alias kcsysding='kubectl_alias --namespace=kube-system describe ingress'
  alias kcrming='kubectl_alias delete ingress'
  alias kcsysrming='kubectl_alias --namespace=kube-system delete ingress'
  alias kcgcm='kubectl_alias get configmap'
  alias kcsysgcm='kubectl_alias --namespace=kube-system get configmap'
  alias kcdcm='kubectl_alias describe configmap'
  alias kcsysdcm='kubectl_alias --namespace=kube-system describe configmap'
  alias kcrmcm='kubectl_alias delete configmap'
  alias kcsysrmcm='kubectl_alias --namespace=kube-system delete configmap'
  alias kcgsec='kubectl_alias get secret'
  alias kcsysgsec='kubectl_alias --namespace=kube-system get secret'
  alias kcdsec='kubectl_alias describe secret'
  alias kcsysdsec='kubectl_alias --namespace=kube-system describe secret'
  alias kcrmsec='kubectl_alias delete secret'
  alias kcsysrmsec='kubectl_alias --namespace=kube-system delete secret'
  alias kcgno='kubectl_alias get nodes'
  alias kcdno='kubectl_alias describe nodes'
  alias kcgns='kubectl_alias get namespaces'
  alias kcdns='kubectl_alias describe namespaces'
  alias kcrmns='kubectl_alias delete namespaces'
  alias kcgoyaml='kubectl_alias get -o=yaml'
  alias kcsysgoyaml='kubectl_alias --namespace=kube-system get -o=yaml'
  alias kcgpooyaml='kubectl_alias get pods -o=yaml'
  alias kcsysgpooyaml='kubectl_alias --namespace=kube-system get pods -o=yaml'
  alias kcgdepoyaml='kubectl_alias get deployment -o=yaml'
  alias kcsysgdepoyaml='kubectl_alias --namespace=kube-system get deployment -o=yaml'
  alias kcgsvcoyaml='kubectl_alias get service -o=yaml'
  alias kcsysgsvcoyaml='kubectl_alias --namespace=kube-system get service -o=yaml'
  alias kcgingoyaml='kubectl_alias get ingress -o=yaml'
  alias kcsysgingoyaml='kubectl_alias --namespace=kube-system get ingress -o=yaml'
  alias kcgcmoyaml='kubectl_alias get configmap -o=yaml'
  alias kcsysgcmoyaml='kubectl_alias --namespace=kube-system get configmap -o=yaml'
  alias kcgsecoyaml='kubectl_alias get secret -o=yaml'
  alias kcsysgsecoyaml='kubectl_alias --namespace=kube-system get secret -o=yaml'
  alias kcgnooyaml='kubectl_alias get nodes -o=yaml'
  alias kcgnsoyaml='kubectl_alias get namespaces -o=yaml'
  alias kcgowide='kubectl_alias get -o=wide'
  alias kcsysgowide='kubectl_alias --namespace=kube-system get -o=wide'
  alias kcgpoowide='kubectl_alias get pods -o=wide'
  alias kcsysgpoowide='kubectl_alias --namespace=kube-system get pods -o=wide'
  alias kcgdepowide='kubectl_alias get deployment -o=wide'
  alias kcsysgdepowide='kubectl_alias --namespace=kube-system get deployment -o=wide'
  alias kcgsvcowide='kubectl_alias get service -o=wide'
  alias kcsysgsvcowide='kubectl_alias --namespace=kube-system get service -o=wide'
  alias kcgingowide='kubectl_alias get ingress -o=wide'
  alias kcsysgingowide='kubectl_alias --namespace=kube-system get ingress -o=wide'
  alias kcgcmowide='kubectl_alias get configmap -o=wide'
  alias kcsysgcmowide='kubectl_alias --namespace=kube-system get configmap -o=wide'
  alias kcgsecowide='kubectl_alias get secret -o=wide'
  alias kcsysgsecowide='kubectl_alias --namespace=kube-system get secret -o=wide'
  alias kcgnoowide='kubectl_alias get nodes -o=wide'
  alias kcgnsowide='kubectl_alias get namespaces -o=wide'
  alias kcgojson='kubectl_alias get -o=json'
  alias kcsysgojson='kubectl_alias --namespace=kube-system get -o=json'
  alias kcgpoojson='kubectl_alias get pods -o=json'
  alias kcsysgpoojson='kubectl_alias --namespace=kube-system get pods -o=json'
  alias kcgdepojson='kubectl_alias get deployment -o=json'
  alias kcsysgdepojson='kubectl_alias --namespace=kube-system get deployment -o=json'
  alias kcgsvcojson='kubectl_alias get service -o=json'
  alias kcsysgsvcojson='kubectl_alias --namespace=kube-system get service -o=json'
  alias kcgingojson='kubectl_alias get ingress -o=json'
  alias kcsysgingojson='kubectl_alias --namespace=kube-system get ingress -o=json'
  alias kcgcmojson='kubectl_alias get configmap -o=json'
  alias kcsysgcmojson='kubectl_alias --namespace=kube-system get configmap -o=json'
  alias kcgsecojson='kubectl_alias get secret -o=json'
  alias kcsysgsecojson='kubectl_alias --namespace=kube-system get secret -o=json'
  alias kcgnoojson='kubectl_alias get nodes -o=json'
  alias kcgnsojson='kubectl_alias get namespaces -o=json'
  alias kcgall='kubectl_alias get --all-namespaces'
  alias kcdall='kubectl_alias describe --all-namespaces'
  alias kcgpoall='kubectl_alias get pods --all-namespaces'
  alias kcdpoall='kubectl_alias describe pods --all-namespaces'
  alias kcgdepall='kubectl_alias get deployment --all-namespaces'
  alias kcddepall='kubectl_alias describe deployment --all-namespaces'
  alias kcgsvcall='kubectl_alias get service --all-namespaces'
  alias kcdsvcall='kubectl_alias describe service --all-namespaces'
  alias kcgingall='kubectl_alias get ingress --all-namespaces'
  alias kcdingall='kubectl_alias describe ingress --all-namespaces'
  alias kcgcmall='kubectl_alias get configmap --all-namespaces'
  alias kcdcmall='kubectl_alias describe configmap --all-namespaces'
  alias kcgsecall='kubectl_alias get secret --all-namespaces'
  alias kcdsecall='kubectl_alias describe secret --all-namespaces'
  alias kcgnsall='kubectl_alias get namespaces --all-namespaces'
  alias kcdnsall='kubectl_alias describe namespaces --all-namespaces'
  alias kcgsl='kubectl_alias get --show-labels'
  alias kcsysgsl='kubectl_alias --namespace=kube-system get --show-labels'
  alias kcgposl='kubectl_alias get pods --show-labels'
  alias kcsysgposl='kubectl_alias --namespace=kube-system get pods --show-labels'
  alias kcgdepsl='kubectl_alias get deployment --show-labels'
  alias kcsysgdepsl='kubectl_alias --namespace=kube-system get deployment --show-labels'
  alias kcrmall='kubectl_alias delete --all'
  alias kcsysrmall='kubectl_alias --namespace=kube-system delete --all'
  alias kcrmpoall='kubectl_alias delete pods --all'
  alias kcsysrmpoall='kubectl_alias --namespace=kube-system delete pods --all'
  alias kcrmdepall='kubectl_alias delete deployment --all'
  alias kcsysrmdepall='kubectl_alias --namespace=kube-system delete deployment --all'
  alias kcrmsvcall='kubectl_alias delete service --all'
  alias kcsysrmsvcall='kubectl_alias --namespace=kube-system delete service --all'
  alias kcrmingall='kubectl_alias delete ingress --all'
  alias kcsysrmingall='kubectl_alias --namespace=kube-system delete ingress --all'
  alias kcrmcmall='kubectl_alias delete configmap --all'
  alias kcsysrmcmall='kubectl_alias --namespace=kube-system delete configmap --all'
  alias kcrmsecall='kubectl_alias delete secret --all'
  alias kcsysrmsecall='kubectl_alias --namespace=kube-system delete secret --all'
  alias kcrmnsall='kubectl_alias delete namespaces --all'
  alias kcgw='kubectl_alias get --watch'
  alias kcsysgw='kubectl_alias --namespace=kube-system get --watch'
  alias kcgpow='kubectl_alias get pods --watch'
  alias kcsysgpow='kubectl_alias --namespace=kube-system get pods --watch'
  alias kcgdepw='kubectl_alias get deployment --watch'
  alias kcsysgdepw='kubectl_alias --namespace=kube-system get deployment --watch'
  alias kcgsvcw='kubectl_alias get service --watch'
  alias kcsysgsvcw='kubectl_alias --namespace=kube-system get service --watch'
  alias kcgingw='kubectl_alias get ingress --watch'
  alias kcsysgingw='kubectl_alias --namespace=kube-system get ingress --watch'
  alias kcgcmw='kubectl_alias get configmap --watch'
  alias kcsysgcmw='kubectl_alias --namespace=kube-system get configmap --watch'
  alias kcgsecw='kubectl_alias get secret --watch'
  alias kcsysgsecw='kubectl_alias --namespace=kube-system get secret --watch'
  alias kcgnow='kubectl_alias get nodes --watch'
  alias kcgnsw='kubectl_alias get namespaces --watch'
  alias kcgoyamlall='kubectl_alias get -o=yaml --all-namespaces'
  alias kcgpooyamlall='kubectl_alias get pods -o=yaml --all-namespaces'
  alias kcgdepoyamlall='kubectl_alias get deployment -o=yaml --all-namespaces'
  alias kcgsvcoyamlall='kubectl_alias get service -o=yaml --all-namespaces'
  alias kcgingoyamlall='kubectl_alias get ingress -o=yaml --all-namespaces'
  alias kcgcmoyamlall='kubectl_alias get configmap -o=yaml --all-namespaces'
  alias kcgsecoyamlall='kubectl_alias get secret -o=yaml --all-namespaces'
  alias kcgnsoyamlall='kubectl_alias get namespaces -o=yaml --all-namespaces'
  alias kcgalloyaml='kubectl_alias get --all-namespaces -o=yaml'
  alias kcgpoalloyaml='kubectl_alias get pods --all-namespaces -o=yaml'
  alias kcgdepalloyaml='kubectl_alias get deployment --all-namespaces -o=yaml'
  alias kcgsvcalloyaml='kubectl_alias get service --all-namespaces -o=yaml'
  alias kcgingalloyaml='kubectl_alias get ingress --all-namespaces -o=yaml'
  alias kcgcmalloyaml='kubectl_alias get configmap --all-namespaces -o=yaml'
  alias kcgsecalloyaml='kubectl_alias get secret --all-namespaces -o=yaml'
  alias kcgnsalloyaml='kubectl_alias get namespaces --all-namespaces -o=yaml'
  alias kcgwoyaml='kubectl_alias get --watch -o=yaml'
  alias kcsysgwoyaml='kubectl_alias --namespace=kube-system get --watch -o=yaml'
  alias kcgpowoyaml='kubectl_alias get pods --watch -o=yaml'
  alias kcsysgpowoyaml='kubectl_alias --namespace=kube-system get pods --watch -o=yaml'
  alias kcgdepwoyaml='kubectl_alias get deployment --watch -o=yaml'
  alias kcsysgdepwoyaml='kubectl_alias --namespace=kube-system get deployment --watch -o=yaml'
  alias kcgsvcwoyaml='kubectl_alias get service --watch -o=yaml'
  alias kcsysgsvcwoyaml='kubectl_alias --namespace=kube-system get service --watch -o=yaml'
  alias kcgingwoyaml='kubectl_alias get ingress --watch -o=yaml'
  alias kcsysgingwoyaml='kubectl_alias --namespace=kube-system get ingress --watch -o=yaml'
  alias kcgcmwoyaml='kubectl_alias get configmap --watch -o=yaml'
  alias kcsysgcmwoyaml='kubectl_alias --namespace=kube-system get configmap --watch -o=yaml'
  alias kcgsecwoyaml='kubectl_alias get secret --watch -o=yaml'
  alias kcsysgsecwoyaml='kubectl_alias --namespace=kube-system get secret --watch -o=yaml'
  alias kcgnowoyaml='kubectl_alias get nodes --watch -o=yaml'
  alias kcgnswoyaml='kubectl_alias get namespaces --watch -o=yaml'
  alias kcgowideall='kubectl_alias get -o=wide --all-namespaces'
  alias kcgpoowideall='kubectl_alias get pods -o=wide --all-namespaces'
  alias kcgdepowideall='kubectl_alias get deployment -o=wide --all-namespaces'
  alias kcgsvcowideall='kubectl_alias get service -o=wide --all-namespaces'
  alias kcgingowideall='kubectl_alias get ingress -o=wide --all-namespaces'
  alias kcgcmowideall='kubectl_alias get configmap -o=wide --all-namespaces'
  alias kcgsecowideall='kubectl_alias get secret -o=wide --all-namespaces'
  alias kcgnsowideall='kubectl_alias get namespaces -o=wide --all-namespaces'
  alias kcgallowide='kubectl_alias get --all-namespaces -o=wide'
  alias kcgpoallowide='kubectl_alias get pods --all-namespaces -o=wide'
  alias kcgdepallowide='kubectl_alias get deployment --all-namespaces -o=wide'
  alias kcgsvcallowide='kubectl_alias get service --all-namespaces -o=wide'
  alias kcgingallowide='kubectl_alias get ingress --all-namespaces -o=wide'
  alias kcgcmallowide='kubectl_alias get configmap --all-namespaces -o=wide'
  alias kcgsecallowide='kubectl_alias get secret --all-namespaces -o=wide'
  alias kcgnsallowide='kubectl_alias get namespaces --all-namespaces -o=wide'
  alias kcgowidesl='kubectl_alias get -o=wide --show-labels'
  alias kcsysgowidesl='kubectl_alias --namespace=kube-system get -o=wide --show-labels'
  alias kcgpoowidesl='kubectl_alias get pods -o=wide --show-labels'
  alias kcsysgpoowidesl='kubectl_alias --namespace=kube-system get pods -o=wide --show-labels'
  alias kcgdepowidesl='kubectl_alias get deployment -o=wide --show-labels'
  alias kcsysgdepowidesl='kubectl_alias --namespace=kube-system get deployment -o=wide --show-labels'
  alias kcgslowide='kubectl_alias get --show-labels -o=wide'
  alias kcsysgslowide='kubectl_alias --namespace=kube-system get --show-labels -o=wide'
  alias kcgposlowide='kubectl_alias get pods --show-labels -o=wide'
  alias kcsysgposlowide='kubectl_alias --namespace=kube-system get pods --show-labels -o=wide'
  alias kcgdepslowide='kubectl_alias get deployment --show-labels -o=wide'
  alias kcsysgdepslowide='kubectl_alias --namespace=kube-system get deployment --show-labels -o=wide'
  alias kcgwowide='kubectl_alias get --watch -o=wide'
  alias kcsysgwowide='kubectl_alias --namespace=kube-system get --watch -o=wide'
  alias kcgpowowide='kubectl_alias get pods --watch -o=wide'
  alias kcsysgpowowide='kubectl_alias --namespace=kube-system get pods --watch -o=wide'
  alias kcgdepwowide='kubectl_alias get deployment --watch -o=wide'
  alias kcsysgdepwowide='kubectl_alias --namespace=kube-system get deployment --watch -o=wide'
  alias kcgsvcwowide='kubectl_alias get service --watch -o=wide'
  alias kcsysgsvcwowide='kubectl_alias --namespace=kube-system get service --watch -o=wide'
  alias kcgingwowide='kubectl_alias get ingress --watch -o=wide'
  alias kcsysgingwowide='kubectl_alias --namespace=kube-system get ingress --watch -o=wide'
  alias kcgcmwowide='kubectl_alias get configmap --watch -o=wide'
  alias kcsysgcmwowide='kubectl_alias --namespace=kube-system get configmap --watch -o=wide'
  alias kcgsecwowide='kubectl_alias get secret --watch -o=wide'
  alias kcsysgsecwowide='kubectl_alias --namespace=kube-system get secret --watch -o=wide'
  alias kcgnowowide='kubectl_alias get nodes --watch -o=wide'
  alias kcgnswowide='kubectl_alias get namespaces --watch -o=wide'
  alias kcgojsonall='kubectl_alias get -o=json --all-namespaces'
  alias kcgpoojsonall='kubectl_alias get pods -o=json --all-namespaces'
  alias kcgdepojsonall='kubectl_alias get deployment -o=json --all-namespaces'
  alias kcgsvcojsonall='kubectl_alias get service -o=json --all-namespaces'
  alias kcgingojsonall='kubectl_alias get ingress -o=json --all-namespaces'
  alias kcgcmojsonall='kubectl_alias get configmap -o=json --all-namespaces'
  alias kcgsecojsonall='kubectl_alias get secret -o=json --all-namespaces'
  alias kcgnsojsonall='kubectl_alias get namespaces -o=json --all-namespaces'
  alias kcgallojson='kubectl_alias get --all-namespaces -o=json'
  alias kcgpoallojson='kubectl_alias get pods --all-namespaces -o=json'
  alias kcgdepallojson='kubectl_alias get deployment --all-namespaces -o=json'
  alias kcgsvcallojson='kubectl_alias get service --all-namespaces -o=json'
  alias kcgingallojson='kubectl_alias get ingress --all-namespaces -o=json'
  alias kcgcmallojson='kubectl_alias get configmap --all-namespaces -o=json'
  alias kcgsecallojson='kubectl_alias get secret --all-namespaces -o=json'
  alias kcgnsallojson='kubectl_alias get namespaces --all-namespaces -o=json'
  alias kcgwojson='kubectl_alias get --watch -o=json'
  alias kcsysgwojson='kubectl_alias --namespace=kube-system get --watch -o=json'
  alias kcgpowojson='kubectl_alias get pods --watch -o=json'
  alias kcsysgpowojson='kubectl_alias --namespace=kube-system get pods --watch -o=json'
  alias kcgdepwojson='kubectl_alias get deployment --watch -o=json'
  alias kcsysgdepwojson='kubectl_alias --namespace=kube-system get deployment --watch -o=json'
  alias kcgsvcwojson='kubectl_alias get service --watch -o=json'
  alias kcsysgsvcwojson='kubectl_alias --namespace=kube-system get service --watch -o=json'
  alias kcgingwojson='kubectl_alias get ingress --watch -o=json'
  alias kcsysgingwojson='kubectl_alias --namespace=kube-system get ingress --watch -o=json'
  alias kcgcmwojson='kubectl_alias get configmap --watch -o=json'
  alias kcsysgcmwojson='kubectl_alias --namespace=kube-system get configmap --watch -o=json'
  alias kcgsecwojson='kubectl_alias get secret --watch -o=json'
  alias kcsysgsecwojson='kubectl_alias --namespace=kube-system get secret --watch -o=json'
  alias kcgnowojson='kubectl_alias get nodes --watch -o=json'
  alias kcgnswojson='kubectl_alias get namespaces --watch -o=json'
  alias kcgallsl='kubectl_alias get --all-namespaces --show-labels'
  alias kcgpoallsl='kubectl_alias get pods --all-namespaces --show-labels'
  alias kcgdepallsl='kubectl_alias get deployment --all-namespaces --show-labels'
  alias kcgslall='kubectl_alias get --show-labels --all-namespaces'
  alias kcgposlall='kubectl_alias get pods --show-labels --all-namespaces'
  alias kcgdepslall='kubectl_alias get deployment --show-labels --all-namespaces'
  alias kcgallw='kubectl_alias get --all-namespaces --watch'
  alias kcgpoallw='kubectl_alias get pods --all-namespaces --watch'
  alias kcgdepallw='kubectl_alias get deployment --all-namespaces --watch'
  alias kcgsvcallw='kubectl_alias get service --all-namespaces --watch'
  alias kcgingallw='kubectl_alias get ingress --all-namespaces --watch'
  alias kcgcmallw='kubectl_alias get configmap --all-namespaces --watch'
  alias kcgsecallw='kubectl_alias get secret --all-namespaces --watch'
  alias kcgnsallw='kubectl_alias get namespaces --all-namespaces --watch'
  alias kcgwall='kubectl_alias get --watch --all-namespaces'
  alias kcgpowall='kubectl_alias get pods --watch --all-namespaces'
  alias kcgdepwall='kubectl_alias get deployment --watch --all-namespaces'
  alias kcgsvcwall='kubectl_alias get service --watch --all-namespaces'
  alias kcgingwall='kubectl_alias get ingress --watch --all-namespaces'
  alias kcgcmwall='kubectl_alias get configmap --watch --all-namespaces'
  alias kcgsecwall='kubectl_alias get secret --watch --all-namespaces'
  alias kcgnswall='kubectl_alias get namespaces --watch --all-namespaces'
  alias kcgslw='kubectl_alias get --show-labels --watch'
  alias kcsysgslw='kubectl_alias --namespace=kube-system get --show-labels --watch'
  alias kcgposlw='kubectl_alias get pods --show-labels --watch'
  alias kcsysgposlw='kubectl_alias --namespace=kube-system get pods --show-labels --watch'
  alias kcgdepslw='kubectl_alias get deployment --show-labels --watch'
  alias kcsysgdepslw='kubectl_alias --namespace=kube-system get deployment --show-labels --watch'
  alias kcgwsl='kubectl_alias get --watch --show-labels'
  alias kcsysgwsl='kubectl_alias --namespace=kube-system get --watch --show-labels'
  alias kcgpowsl='kubectl_alias get pods --watch --show-labels'
  alias kcsysgpowsl='kubectl_alias --namespace=kube-system get pods --watch --show-labels'
  alias kcgdepwsl='kubectl_alias get deployment --watch --show-labels'
  alias kcsysgdepwsl='kubectl_alias --namespace=kube-system get deployment --watch --show-labels'
  alias kcgallwoyaml='kubectl_alias get --all-namespaces --watch -o=yaml'
  alias kcgpoallwoyaml='kubectl_alias get pods --all-namespaces --watch -o=yaml'
  alias kcgdepallwoyaml='kubectl_alias get deployment --all-namespaces --watch -o=yaml'
  alias kcgsvcallwoyaml='kubectl_alias get service --all-namespaces --watch -o=yaml'
  alias kcgingallwoyaml='kubectl_alias get ingress --all-namespaces --watch -o=yaml'
  alias kcgcmallwoyaml='kubectl_alias get configmap --all-namespaces --watch -o=yaml'
  alias kcgsecallwoyaml='kubectl_alias get secret --all-namespaces --watch -o=yaml'
  alias kcgnsallwoyaml='kubectl_alias get namespaces --all-namespaces --watch -o=yaml'
  alias kcgwoyamlall='kubectl_alias get --watch -o=yaml --all-namespaces'
  alias kcgpowoyamlall='kubectl_alias get pods --watch -o=yaml --all-namespaces'
  alias kcgdepwoyamlall='kubectl_alias get deployment --watch -o=yaml --all-namespaces'
  alias kcgsvcwoyamlall='kubectl_alias get service --watch -o=yaml --all-namespaces'
  alias kcgingwoyamlall='kubectl_alias get ingress --watch -o=yaml --all-namespaces'
  alias kcgcmwoyamlall='kubectl_alias get configmap --watch -o=yaml --all-namespaces'
  alias kcgsecwoyamlall='kubectl_alias get secret --watch -o=yaml --all-namespaces'
  alias kcgnswoyamlall='kubectl_alias get namespaces --watch -o=yaml --all-namespaces'
  alias kcgwalloyaml='kubectl_alias get --watch --all-namespaces -o=yaml'
  alias kcgpowalloyaml='kubectl_alias get pods --watch --all-namespaces -o=yaml'
  alias kcgdepwalloyaml='kubectl_alias get deployment --watch --all-namespaces -o=yaml'
  alias kcgsvcwalloyaml='kubectl_alias get service --watch --all-namespaces -o=yaml'
  alias kcgingwalloyaml='kubectl_alias get ingress --watch --all-namespaces -o=yaml'
  alias kcgcmwalloyaml='kubectl_alias get configmap --watch --all-namespaces -o=yaml'
  alias kcgsecwalloyaml='kubectl_alias get secret --watch --all-namespaces -o=yaml'
  alias kcgnswalloyaml='kubectl_alias get namespaces --watch --all-namespaces -o=yaml'
  alias kcgowideallsl='kubectl_alias get -o=wide --all-namespaces --show-labels'
  alias kcgpoowideallsl='kubectl_alias get pods -o=wide --all-namespaces --show-labels'
  alias kcgdepowideallsl='kubectl_alias get deployment -o=wide --all-namespaces --show-labels'
  alias kcgowideslall='kubectl_alias get -o=wide --show-labels --all-namespaces'
  alias kcgpoowideslall='kubectl_alias get pods -o=wide --show-labels --all-namespaces'
  alias kcgdepowideslall='kubectl_alias get deployment -o=wide --show-labels --all-namespaces'
  alias kcgallowidesl='kubectl_alias get --all-namespaces -o=wide --show-labels'
  alias kcgpoallowidesl='kubectl_alias get pods --all-namespaces -o=wide --show-labels'
  alias kcgdepallowidesl='kubectl_alias get deployment --all-namespaces -o=wide --show-labels'
  alias kcgallslowide='kubectl_alias get --all-namespaces --show-labels -o=wide'
  alias kcgpoallslowide='kubectl_alias get pods --all-namespaces --show-labels -o=wide'
  alias kcgdepallslowide='kubectl_alias get deployment --all-namespaces --show-labels -o=wide'
  alias kcgslowideall='kubectl_alias get --show-labels -o=wide --all-namespaces'
  alias kcgposlowideall='kubectl_alias get pods --show-labels -o=wide --all-namespaces'
  alias kcgdepslowideall='kubectl_alias get deployment --show-labels -o=wide --all-namespaces'
  alias kcgslallowide='kubectl_alias get --show-labels --all-namespaces -o=wide'
  alias kcgposlallowide='kubectl_alias get pods --show-labels --all-namespaces -o=wide'
  alias kcgdepslallowide='kubectl_alias get deployment --show-labels --all-namespaces -o=wide'
  alias kcgallwowide='kubectl_alias get --all-namespaces --watch -o=wide'
  alias kcgpoallwowide='kubectl_alias get pods --all-namespaces --watch -o=wide'
  alias kcgdepallwowide='kubectl_alias get deployment --all-namespaces --watch -o=wide'
  alias kcgsvcallwowide='kubectl_alias get service --all-namespaces --watch -o=wide'
  alias kcgingallwowide='kubectl_alias get ingress --all-namespaces --watch -o=wide'
  alias kcgcmallwowide='kubectl_alias get configmap --all-namespaces --watch -o=wide'
  alias kcgsecallwowide='kubectl_alias get secret --all-namespaces --watch -o=wide'
  alias kcgnsallwowide='kubectl_alias get namespaces --all-namespaces --watch -o=wide'
  alias kcgwowideall='kubectl_alias get --watch -o=wide --all-namespaces'
  alias kcgpowowideall='kubectl_alias get pods --watch -o=wide --all-namespaces'
  alias kcgdepwowideall='kubectl_alias get deployment --watch -o=wide --all-namespaces'
  alias kcgsvcwowideall='kubectl_alias get service --watch -o=wide --all-namespaces'
  alias kcgingwowideall='kubectl_alias get ingress --watch -o=wide --all-namespaces'
  alias kcgcmwowideall='kubectl_alias get configmap --watch -o=wide --all-namespaces'
  alias kcgsecwowideall='kubectl_alias get secret --watch -o=wide --all-namespaces'
  alias kcgnswowideall='kubectl_alias get namespaces --watch -o=wide --all-namespaces'
  alias kcgwallowide='kubectl_alias get --watch --all-namespaces -o=wide'
  alias kcgpowallowide='kubectl_alias get pods --watch --all-namespaces -o=wide'
  alias kcgdepwallowide='kubectl_alias get deployment --watch --all-namespaces -o=wide'
  alias kcgsvcwallowide='kubectl_alias get service --watch --all-namespaces -o=wide'
  alias kcgingwallowide='kubectl_alias get ingress --watch --all-namespaces -o=wide'
  alias kcgcmwallowide='kubectl_alias get configmap --watch --all-namespaces -o=wide'
  alias kcgsecwallowide='kubectl_alias get secret --watch --all-namespaces -o=wide'
  alias kcgnswallowide='kubectl_alias get namespaces --watch --all-namespaces -o=wide'
  alias kcgslwowide='kubectl_alias get --show-labels --watch -o=wide'
  alias kcsysgslwowide='kubectl_alias --namespace=kube-system get --show-labels --watch -o=wide'
  alias kcgposlwowide='kubectl_alias get pods --show-labels --watch -o=wide'
  alias kcsysgposlwowide='kubectl_alias --namespace=kube-system get pods --show-labels --watch -o=wide'
  alias kcgdepslwowide='kubectl_alias get deployment --show-labels --watch -o=wide'
  alias kcsysgdepslwowide='kubectl_alias --namespace=kube-system get deployment --show-labels --watch -o=wide'
  alias kcgwowidesl='kubectl_alias get --watch -o=wide --show-labels'
  alias kcsysgwowidesl='kubectl_alias --namespace=kube-system get --watch -o=wide --show-labels'
  alias kcgpowowidesl='kubectl_alias get pods --watch -o=wide --show-labels'
  alias kcsysgpowowidesl='kubectl_alias --namespace=kube-system get pods --watch -o=wide --show-labels'
  alias kcgdepwowidesl='kubectl_alias get deployment --watch -o=wide --show-labels'
  alias kcsysgdepwowidesl='kubectl_alias --namespace=kube-system get deployment --watch -o=wide --show-labels'
  alias kcgwslowide='kubectl_alias get --watch --show-labels -o=wide'
  alias kcsysgwslowide='kubectl_alias --namespace=kube-system get --watch --show-labels -o=wide'
  alias kcgpowslowide='kubectl_alias get pods --watch --show-labels -o=wide'
  alias kcsysgpowslowide='kubectl_alias --namespace=kube-system get pods --watch --show-labels -o=wide'
  alias kcgdepwslowide='kubectl_alias get deployment --watch --show-labels -o=wide'
  alias kcsysgdepwslowide='kubectl_alias --namespace=kube-system get deployment --watch --show-labels -o=wide'
  alias kcgallwojson='kubectl_alias get --all-namespaces --watch -o=json'
  alias kcgpoallwojson='kubectl_alias get pods --all-namespaces --watch -o=json'
  alias kcgdepallwojson='kubectl_alias get deployment --all-namespaces --watch -o=json'
  alias kcgsvcallwojson='kubectl_alias get service --all-namespaces --watch -o=json'
  alias kcgingallwojson='kubectl_alias get ingress --all-namespaces --watch -o=json'
  alias kcgcmallwojson='kubectl_alias get configmap --all-namespaces --watch -o=json'
  alias kcgsecallwojson='kubectl_alias get secret --all-namespaces --watch -o=json'
  alias kcgnsallwojson='kubectl_alias get namespaces --all-namespaces --watch -o=json'
  alias kcgwojsonall='kubectl_alias get --watch -o=json --all-namespaces'
  alias kcgpowojsonall='kubectl_alias get pods --watch -o=json --all-namespaces'
  alias kcgdepwojsonall='kubectl_alias get deployment --watch -o=json --all-namespaces'
  alias kcgsvcwojsonall='kubectl_alias get service --watch -o=json --all-namespaces'
  alias kcgingwojsonall='kubectl_alias get ingress --watch -o=json --all-namespaces'
  alias kcgcmwojsonall='kubectl_alias get configmap --watch -o=json --all-namespaces'
  alias kcgsecwojsonall='kubectl_alias get secret --watch -o=json --all-namespaces'
  alias kcgnswojsonall='kubectl_alias get namespaces --watch -o=json --all-namespaces'
  alias kcgwallojson='kubectl_alias get --watch --all-namespaces -o=json'
  alias kcgpowallojson='kubectl_alias get pods --watch --all-namespaces -o=json'
  alias kcgdepwallojson='kubectl_alias get deployment --watch --all-namespaces -o=json'
  alias kcgsvcwallojson='kubectl_alias get service --watch --all-namespaces -o=json'
  alias kcgingwallojson='kubectl_alias get ingress --watch --all-namespaces -o=json'
  alias kcgcmwallojson='kubectl_alias get configmap --watch --all-namespaces -o=json'
  alias kcgsecwallojson='kubectl_alias get secret --watch --all-namespaces -o=json'
  alias kcgnswallojson='kubectl_alias get namespaces --watch --all-namespaces -o=json'
  alias kcgallslw='kubectl_alias get --all-namespaces --show-labels --watch'
  alias kcgpoallslw='kubectl_alias get pods --all-namespaces --show-labels --watch'
  alias kcgdepallslw='kubectl_alias get deployment --all-namespaces --show-labels --watch'
  alias kcgallwsl='kubectl_alias get --all-namespaces --watch --show-labels'
  alias kcgpoallwsl='kubectl_alias get pods --all-namespaces --watch --show-labels'
  alias kcgdepallwsl='kubectl_alias get deployment --all-namespaces --watch --show-labels'
  alias kcgslallw='kubectl_alias get --show-labels --all-namespaces --watch'
  alias kcgposlallw='kubectl_alias get pods --show-labels --all-namespaces --watch'
  alias kcgdepslallw='kubectl_alias get deployment --show-labels --all-namespaces --watch'
  alias kcgslwall='kubectl_alias get --show-labels --watch --all-namespaces'
  alias kcgposlwall='kubectl_alias get pods --show-labels --watch --all-namespaces'
  alias kcgdepslwall='kubectl_alias get deployment --show-labels --watch --all-namespaces'
  alias kcgwallsl='kubectl_alias get --watch --all-namespaces --show-labels'
  alias kcgpowallsl='kubectl_alias get pods --watch --all-namespaces --show-labels'
  alias kcgdepwallsl='kubectl_alias get deployment --watch --all-namespaces --show-labels'
  alias kcgwslall='kubectl_alias get --watch --show-labels --all-namespaces'
  alias kcgpowslall='kubectl_alias get pods --watch --show-labels --all-namespaces'
  alias kcgdepwslall='kubectl_alias get deployment --watch --show-labels --all-namespaces'
  alias kcgallslwowide='kubectl_alias get --all-namespaces --show-labels --watch -o=wide'
  alias kcgpoallslwowide='kubectl_alias get pods --all-namespaces --show-labels --watch -o=wide'
  alias kcgdepallslwowide='kubectl_alias get deployment --all-namespaces --show-labels --watch -o=wide'
  alias kcgallwowidesl='kubectl_alias get --all-namespaces --watch -o=wide --show-labels'
  alias kcgpoallwowidesl='kubectl_alias get pods --all-namespaces --watch -o=wide --show-labels'
  alias kcgdepallwowidesl='kubectl_alias get deployment --all-namespaces --watch -o=wide --show-labels'
  alias kcgallwslowide='kubectl_alias get --all-namespaces --watch --show-labels -o=wide'
  alias kcgpoallwslowide='kubectl_alias get pods --all-namespaces --watch --show-labels -o=wide'
  alias kcgdepallwslowide='kubectl_alias get deployment --all-namespaces --watch --show-labels -o=wide'
  alias kcgslallwowide='kubectl_alias get --show-labels --all-namespaces --watch -o=wide'
  alias kcgposlallwowide='kubectl_alias get pods --show-labels --all-namespaces --watch -o=wide'
  alias kcgdepslallwowide='kubectl_alias get deployment --show-labels --all-namespaces --watch -o=wide'
  alias kcgslwowideall='kubectl_alias get --show-labels --watch -o=wide --all-namespaces'
  alias kcgposlwowideall='kubectl_alias get pods --show-labels --watch -o=wide --all-namespaces'
  alias kcgdepslwowideall='kubectl_alias get deployment --show-labels --watch -o=wide --all-namespaces'
  alias kcgslwallowide='kubectl_alias get --show-labels --watch --all-namespaces -o=wide'
  alias kcgposlwallowide='kubectl_alias get pods --show-labels --watch --all-namespaces -o=wide'
  alias kcgdepslwallowide='kubectl_alias get deployment --show-labels --watch --all-namespaces -o=wide'
  alias kcgwowideallsl='kubectl_alias get --watch -o=wide --all-namespaces --show-labels'
  alias kcgpowowideallsl='kubectl_alias get pods --watch -o=wide --all-namespaces --show-labels'
  alias kcgdepwowideallsl='kubectl_alias get deployment --watch -o=wide --all-namespaces --show-labels'
  alias kcgwowideslall='kubectl_alias get --watch -o=wide --show-labels --all-namespaces'
  alias kcgpowowideslall='kubectl_alias get pods --watch -o=wide --show-labels --all-namespaces'
  alias kcgdepwowideslall='kubectl_alias get deployment --watch -o=wide --show-labels --all-namespaces'
  alias kcgwallowidesl='kubectl_alias get --watch --all-namespaces -o=wide --show-labels'
  alias kcgpowallowidesl='kubectl_alias get pods --watch --all-namespaces -o=wide --show-labels'
  alias kcgdepwallowidesl='kubectl_alias get deployment --watch --all-namespaces -o=wide --show-labels'
  alias kcgwallslowide='kubectl_alias get --watch --all-namespaces --show-labels -o=wide'
  alias kcgpowallslowide='kubectl_alias get pods --watch --all-namespaces --show-labels -o=wide'
  alias kcgdepwallslowide='kubectl_alias get deployment --watch --all-namespaces --show-labels -o=wide'
  alias kcgwslowideall='kubectl_alias get --watch --show-labels -o=wide --all-namespaces'
  alias kcgpowslowideall='kubectl_alias get pods --watch --show-labels -o=wide --all-namespaces'
  alias kcgdepwslowideall='kubectl_alias get deployment --watch --show-labels -o=wide --all-namespaces'
  alias kcgwslallowide='kubectl_alias get --watch --show-labels --all-namespaces -o=wide'
  alias kcgpowslallowide='kubectl_alias get pods --watch --show-labels --all-namespaces -o=wide'
  alias kcgdepwslallowide='kubectl_alias get deployment --watch --show-labels --all-namespaces -o=wide'
  alias kcgf='kubectl_alias get --recursive -f'
  alias kcdf='kubectl_alias describe --recursive -f'
  alias kcrmf='kubectl_alias delete --recursive -f'
  alias kcgoyamlf='kubectl_alias get -o=yaml --recursive -f'
  alias kcgowidef='kubectl_alias get -o=wide --recursive -f'
  alias kcgojsonf='kubectl_alias get -o=json --recursive -f'
  alias kcgslf='kubectl_alias get --show-labels --recursive -f'
  alias kcgwf='kubectl_alias get --watch --recursive -f'
  alias kcgwoyamlf='kubectl_alias get --watch -o=yaml --recursive -f'
  alias kcgowideslf='kubectl_alias get -o=wide --show-labels --recursive -f'
  alias kcgslowidef='kubectl_alias get --show-labels -o=wide --recursive -f'
  alias kcgwowidef='kubectl_alias get --watch -o=wide --recursive -f'
  alias kcgwojsonf='kubectl_alias get --watch -o=json --recursive -f'
  alias kcgslwf='kubectl_alias get --show-labels --watch --recursive -f'
  alias kcgwslf='kubectl_alias get --watch --show-labels --recursive -f'
  alias kcgslwowidef='kubectl_alias get --show-labels --watch -o=wide --recursive -f'
  alias kcgwowideslf='kubectl_alias get --watch -o=wide --show-labels --recursive -f'
  alias kcgwslowidef='kubectl_alias get --watch --show-labels -o=wide --recursive -f'
  alias kcgl='kubectl_alias get -l'
  alias kcsysgl='kubectl_alias --namespace=kube-system get -l'
  alias kcdl='kubectl_alias describe -l'
  alias kcsysdl='kubectl_alias --namespace=kube-system describe -l'
  alias kcrml='kubectl_alias delete -l'
  alias kcsysrml='kubectl_alias --namespace=kube-system delete -l'
  alias kcgpol='kubectl_alias get pods -l'
  alias kcsysgpol='kubectl_alias --namespace=kube-system get pods -l'
  alias kcdpol='kubectl_alias describe pods -l'
  alias kcsysdpol='kubectl_alias --namespace=kube-system describe pods -l'
  alias kcrmpol='kubectl_alias delete pods -l'
  alias kcsysrmpol='kubectl_alias --namespace=kube-system delete pods -l'
  alias kcgdepl='kubectl_alias get deployment -l'
  alias kcsysgdepl='kubectl_alias --namespace=kube-system get deployment -l'
  alias kcddepl='kubectl_alias describe deployment -l'
  alias kcsysddepl='kubectl_alias --namespace=kube-system describe deployment -l'
  alias kcrmdepl='kubectl_alias delete deployment -l'
  alias kcsysrmdepl='kubectl_alias --namespace=kube-system delete deployment -l'
  alias kcgsvcl='kubectl_alias get service -l'
  alias kcsysgsvcl='kubectl_alias --namespace=kube-system get service -l'
  alias kcdsvcl='kubectl_alias describe service -l'
  alias kcsysdsvcl='kubectl_alias --namespace=kube-system describe service -l'
  alias kcrmsvcl='kubectl_alias delete service -l'
  alias kcsysrmsvcl='kubectl_alias --namespace=kube-system delete service -l'
  alias kcgingl='kubectl_alias get ingress -l'
  alias kcsysgingl='kubectl_alias --namespace=kube-system get ingress -l'
  alias kcdingl='kubectl_alias describe ingress -l'
  alias kcsysdingl='kubectl_alias --namespace=kube-system describe ingress -l'
  alias kcrmingl='kubectl_alias delete ingress -l'
  alias kcsysrmingl='kubectl_alias --namespace=kube-system delete ingress -l'
  alias kcgcml='kubectl_alias get configmap -l'
  alias kcsysgcml='kubectl_alias --namespace=kube-system get configmap -l'
  alias kcdcml='kubectl_alias describe configmap -l'
  alias kcsysdcml='kubectl_alias --namespace=kube-system describe configmap -l'
  alias kcrmcml='kubectl_alias delete configmap -l'
  alias kcsysrmcml='kubectl_alias --namespace=kube-system delete configmap -l'
  alias kcgsecl='kubectl_alias get secret -l'
  alias kcsysgsecl='kubectl_alias --namespace=kube-system get secret -l'
  alias kcdsecl='kubectl_alias describe secret -l'
  alias kcsysdsecl='kubectl_alias --namespace=kube-system describe secret -l'
  alias kcrmsecl='kubectl_alias delete secret -l'
  alias kcsysrmsecl='kubectl_alias --namespace=kube-system delete secret -l'
  alias kcgnol='kubectl_alias get nodes -l'
  alias kcdnol='kubectl_alias describe nodes -l'
  alias kcgnsl='kubectl_alias get namespaces -l'
  alias kcdnsl='kubectl_alias describe namespaces -l'
  alias kcrmnsl='kubectl_alias delete namespaces -l'
  alias kcgoyamll='kubectl_alias get -o=yaml -l'
  alias kcsysgoyamll='kubectl_alias --namespace=kube-system get -o=yaml -l'
  alias kcgpooyamll='kubectl_alias get pods -o=yaml -l'
  alias kcsysgpooyamll='kubectl_alias --namespace=kube-system get pods -o=yaml -l'
  alias kcgdepoyamll='kubectl_alias get deployment -o=yaml -l'
  alias kcsysgdepoyamll='kubectl_alias --namespace=kube-system get deployment -o=yaml -l'
  alias kcgsvcoyamll='kubectl_alias get service -o=yaml -l'
  alias kcsysgsvcoyamll='kubectl_alias --namespace=kube-system get service -o=yaml -l'
  alias kcgingoyamll='kubectl_alias get ingress -o=yaml -l'
  alias kcsysgingoyamll='kubectl_alias --namespace=kube-system get ingress -o=yaml -l'
  alias kcgcmoyamll='kubectl_alias get configmap -o=yaml -l'
  alias kcsysgcmoyamll='kubectl_alias --namespace=kube-system get configmap -o=yaml -l'
  alias kcgsecoyamll='kubectl_alias get secret -o=yaml -l'
  alias kcsysgsecoyamll='kubectl_alias --namespace=kube-system get secret -o=yaml -l'
  alias kcgnooyamll='kubectl_alias get nodes -o=yaml -l'
  alias kcgnsoyamll='kubectl_alias get namespaces -o=yaml -l'
  alias kcgowidel='kubectl_alias get -o=wide -l'
  alias kcsysgowidel='kubectl_alias --namespace=kube-system get -o=wide -l'
  alias kcgpoowidel='kubectl_alias get pods -o=wide -l'
  alias kcsysgpoowidel='kubectl_alias --namespace=kube-system get pods -o=wide -l'
  alias kcgdepowidel='kubectl_alias get deployment -o=wide -l'
  alias kcsysgdepowidel='kubectl_alias --namespace=kube-system get deployment -o=wide -l'
  alias kcgsvcowidel='kubectl_alias get service -o=wide -l'
  alias kcsysgsvcowidel='kubectl_alias --namespace=kube-system get service -o=wide -l'
  alias kcgingowidel='kubectl_alias get ingress -o=wide -l'
  alias kcsysgingowidel='kubectl_alias --namespace=kube-system get ingress -o=wide -l'
  alias kcgcmowidel='kubectl_alias get configmap -o=wide -l'
  alias kcsysgcmowidel='kubectl_alias --namespace=kube-system get configmap -o=wide -l'
  alias kcgsecowidel='kubectl_alias get secret -o=wide -l'
  alias kcsysgsecowidel='kubectl_alias --namespace=kube-system get secret -o=wide -l'
  alias kcgnoowidel='kubectl_alias get nodes -o=wide -l'
  alias kcgnsowidel='kubectl_alias get namespaces -o=wide -l'
  alias kcgojsonl='kubectl_alias get -o=json -l'
  alias kcsysgojsonl='kubectl_alias --namespace=kube-system get -o=json -l'
  alias kcgpoojsonl='kubectl_alias get pods -o=json -l'
  alias kcsysgpoojsonl='kubectl_alias --namespace=kube-system get pods -o=json -l'
  alias kcgdepojsonl='kubectl_alias get deployment -o=json -l'
  alias kcsysgdepojsonl='kubectl_alias --namespace=kube-system get deployment -o=json -l'
  alias kcgsvcojsonl='kubectl_alias get service -o=json -l'
  alias kcsysgsvcojsonl='kubectl_alias --namespace=kube-system get service -o=json -l'
  alias kcgingojsonl='kubectl_alias get ingress -o=json -l'
  alias kcsysgingojsonl='kubectl_alias --namespace=kube-system get ingress -o=json -l'
  alias kcgcmojsonl='kubectl_alias get configmap -o=json -l'
  alias kcsysgcmojsonl='kubectl_alias --namespace=kube-system get configmap -o=json -l'
  alias kcgsecojsonl='kubectl_alias get secret -o=json -l'
  alias kcsysgsecojsonl='kubectl_alias --namespace=kube-system get secret -o=json -l'
  alias kcgnoojsonl='kubectl_alias get nodes -o=json -l'
  alias kcgnsojsonl='kubectl_alias get namespaces -o=json -l'
  alias kcgsll='kubectl_alias get --show-labels -l'
  alias kcsysgsll='kubectl_alias --namespace=kube-system get --show-labels -l'
  alias kcgposll='kubectl_alias get pods --show-labels -l'
  alias kcsysgposll='kubectl_alias --namespace=kube-system get pods --show-labels -l'
  alias kcgdepsll='kubectl_alias get deployment --show-labels -l'
  alias kcsysgdepsll='kubectl_alias --namespace=kube-system get deployment --show-labels -l'
  alias kcgwl='kubectl_alias get --watch -l'
  alias kcsysgwl='kubectl_alias --namespace=kube-system get --watch -l'
  alias kcgpowl='kubectl_alias get pods --watch -l'
  alias kcsysgpowl='kubectl_alias --namespace=kube-system get pods --watch -l'
  alias kcgdepwl='kubectl_alias get deployment --watch -l'
  alias kcsysgdepwl='kubectl_alias --namespace=kube-system get deployment --watch -l'
  alias kcgsvcwl='kubectl_alias get service --watch -l'
  alias kcsysgsvcwl='kubectl_alias --namespace=kube-system get service --watch -l'
  alias kcgingwl='kubectl_alias get ingress --watch -l'
  alias kcsysgingwl='kubectl_alias --namespace=kube-system get ingress --watch -l'
  alias kcgcmwl='kubectl_alias get configmap --watch -l'
  alias kcsysgcmwl='kubectl_alias --namespace=kube-system get configmap --watch -l'
  alias kcgsecwl='kubectl_alias get secret --watch -l'
  alias kcsysgsecwl='kubectl_alias --namespace=kube-system get secret --watch -l'
  alias kcgnowl='kubectl_alias get nodes --watch -l'
  alias kcgnswl='kubectl_alias get namespaces --watch -l'
  alias kcgwoyamll='kubectl_alias get --watch -o=yaml -l'
  alias kcsysgwoyamll='kubectl_alias --namespace=kube-system get --watch -o=yaml -l'
  alias kcgpowoyamll='kubectl_alias get pods --watch -o=yaml -l'
  alias kcsysgpowoyamll='kubectl_alias --namespace=kube-system get pods --watch -o=yaml -l'
  alias kcgdepwoyamll='kubectl_alias get deployment --watch -o=yaml -l'
  alias kcsysgdepwoyamll='kubectl_alias --namespace=kube-system get deployment --watch -o=yaml -l'
  alias kcgsvcwoyamll='kubectl_alias get service --watch -o=yaml -l'
  alias kcsysgsvcwoyamll='kubectl_alias --namespace=kube-system get service --watch -o=yaml -l'
  alias kcgingwoyamll='kubectl_alias get ingress --watch -o=yaml -l'
  alias kcsysgingwoyamll='kubectl_alias --namespace=kube-system get ingress --watch -o=yaml -l'
  alias kcgcmwoyamll='kubectl_alias get configmap --watch -o=yaml -l'
  alias kcsysgcmwoyamll='kubectl_alias --namespace=kube-system get configmap --watch -o=yaml -l'
  alias kcgsecwoyamll='kubectl_alias get secret --watch -o=yaml -l'
  alias kcsysgsecwoyamll='kubectl_alias --namespace=kube-system get secret --watch -o=yaml -l'
  alias kcgnowoyamll='kubectl_alias get nodes --watch -o=yaml -l'
  alias kcgnswoyamll='kubectl_alias get namespaces --watch -o=yaml -l'
  alias kcgowidesll='kubectl_alias get -o=wide --show-labels -l'
  alias kcsysgowidesll='kubectl_alias --namespace=kube-system get -o=wide --show-labels -l'
  alias kcgpoowidesll='kubectl_alias get pods -o=wide --show-labels -l'
  alias kcsysgpoowidesll='kubectl_alias --namespace=kube-system get pods -o=wide --show-labels -l'
  alias kcgdepowidesll='kubectl_alias get deployment -o=wide --show-labels -l'
  alias kcsysgdepowidesll='kubectl_alias --namespace=kube-system get deployment -o=wide --show-labels -l'
  alias kcgslowidel='kubectl_alias get --show-labels -o=wide -l'
  alias kcsysgslowidel='kubectl_alias --namespace=kube-system get --show-labels -o=wide -l'
  alias kcgposlowidel='kubectl_alias get pods --show-labels -o=wide -l'
  alias kcsysgposlowidel='kubectl_alias --namespace=kube-system get pods --show-labels -o=wide -l'
  alias kcgdepslowidel='kubectl_alias get deployment --show-labels -o=wide -l'
  alias kcsysgdepslowidel='kubectl_alias --namespace=kube-system get deployment --show-labels -o=wide -l'
  alias kcgwowidel='kubectl_alias get --watch -o=wide -l'
  alias kcsysgwowidel='kubectl_alias --namespace=kube-system get --watch -o=wide -l'
  alias kcgpowowidel='kubectl_alias get pods --watch -o=wide -l'
  alias kcsysgpowowidel='kubectl_alias --namespace=kube-system get pods --watch -o=wide -l'
  alias kcgdepwowidel='kubectl_alias get deployment --watch -o=wide -l'
  alias kcsysgdepwowidel='kubectl_alias --namespace=kube-system get deployment --watch -o=wide -l'
  alias kcgsvcwowidel='kubectl_alias get service --watch -o=wide -l'
  alias kcsysgsvcwowidel='kubectl_alias --namespace=kube-system get service --watch -o=wide -l'
  alias kcgingwowidel='kubectl_alias get ingress --watch -o=wide -l'
  alias kcsysgingwowidel='kubectl_alias --namespace=kube-system get ingress --watch -o=wide -l'
  alias kcgcmwowidel='kubectl_alias get configmap --watch -o=wide -l'
  alias kcsysgcmwowidel='kubectl_alias --namespace=kube-system get configmap --watch -o=wide -l'
  alias kcgsecwowidel='kubectl_alias get secret --watch -o=wide -l'
  alias kcsysgsecwowidel='kubectl_alias --namespace=kube-system get secret --watch -o=wide -l'
  alias kcgnowowidel='kubectl_alias get nodes --watch -o=wide -l'
  alias kcgnswowidel='kubectl_alias get namespaces --watch -o=wide -l'
  alias kcgwojsonl='kubectl_alias get --watch -o=json -l'
  alias kcsysgwojsonl='kubectl_alias --namespace=kube-system get --watch -o=json -l'
  alias kcgpowojsonl='kubectl_alias get pods --watch -o=json -l'
  alias kcsysgpowojsonl='kubectl_alias --namespace=kube-system get pods --watch -o=json -l'
  alias kcgdepwojsonl='kubectl_alias get deployment --watch -o=json -l'
  alias kcsysgdepwojsonl='kubectl_alias --namespace=kube-system get deployment --watch -o=json -l'
  alias kcgsvcwojsonl='kubectl_alias get service --watch -o=json -l'
  alias kcsysgsvcwojsonl='kubectl_alias --namespace=kube-system get service --watch -o=json -l'
  alias kcgingwojsonl='kubectl_alias get ingress --watch -o=json -l'
  alias kcsysgingwojsonl='kubectl_alias --namespace=kube-system get ingress --watch -o=json -l'
  alias kcgcmwojsonl='kubectl_alias get configmap --watch -o=json -l'
  alias kcsysgcmwojsonl='kubectl_alias --namespace=kube-system get configmap --watch -o=json -l'
  alias kcgsecwojsonl='kubectl_alias get secret --watch -o=json -l'
  alias kcsysgsecwojsonl='kubectl_alias --namespace=kube-system get secret --watch -o=json -l'
  alias kcgnowojsonl='kubectl_alias get nodes --watch -o=json -l'
  alias kcgnswojsonl='kubectl_alias get namespaces --watch -o=json -l'
  alias kcgslwl='kubectl_alias get --show-labels --watch -l'
  alias kcsysgslwl='kubectl_alias --namespace=kube-system get --show-labels --watch -l'
  alias kcgposlwl='kubectl_alias get pods --show-labels --watch -l'
  alias kcsysgposlwl='kubectl_alias --namespace=kube-system get pods --show-labels --watch -l'
  alias kcgdepslwl='kubectl_alias get deployment --show-labels --watch -l'
  alias kcsysgdepslwl='kubectl_alias --namespace=kube-system get deployment --show-labels --watch -l'
  alias kcgwsll='kubectl_alias get --watch --show-labels -l'
  alias kcsysgwsll='kubectl_alias --namespace=kube-system get --watch --show-labels -l'
  alias kcgpowsll='kubectl_alias get pods --watch --show-labels -l'
  alias kcsysgpowsll='kubectl_alias --namespace=kube-system get pods --watch --show-labels -l'
  alias kcgdepwsll='kubectl_alias get deployment --watch --show-labels -l'
  alias kcsysgdepwsll='kubectl_alias --namespace=kube-system get deployment --watch --show-labels -l'
  alias kcgslwowidel='kubectl_alias get --show-labels --watch -o=wide -l'
  alias kcsysgslwowidel='kubectl_alias --namespace=kube-system get --show-labels --watch -o=wide -l'
  alias kcgposlwowidel='kubectl_alias get pods --show-labels --watch -o=wide -l'
  alias kcsysgposlwowidel='kubectl_alias --namespace=kube-system get pods --show-labels --watch -o=wide -l'
  alias kcgdepslwowidel='kubectl_alias get deployment --show-labels --watch -o=wide -l'
  alias kcsysgdepslwowidel='kubectl_alias --namespace=kube-system get deployment --show-labels --watch -o=wide -l'
  alias kcgwowidesll='kubectl_alias get --watch -o=wide --show-labels -l'
  alias kcsysgwowidesll='kubectl_alias --namespace=kube-system get --watch -o=wide --show-labels -l'
  alias kcgpowowidesll='kubectl_alias get pods --watch -o=wide --show-labels -l'
  alias kcsysgpowowidesll='kubectl_alias --namespace=kube-system get pods --watch -o=wide --show-labels -l'
  alias kcgdepwowidesll='kubectl_alias get deployment --watch -o=wide --show-labels -l'
  alias kcsysgdepwowidesll='kubectl_alias --namespace=kube-system get deployment --watch -o=wide --show-labels -l'
  alias kcgwslowidel='kubectl_alias get --watch --show-labels -o=wide -l'
  alias kcsysgwslowidel='kubectl_alias --namespace=kube-system get --watch --show-labels -o=wide -l'
  alias kcgpowslowidel='kubectl_alias get pods --watch --show-labels -o=wide -l'
  alias kcsysgpowslowidel='kubectl_alias --namespace=kube-system get pods --watch --show-labels -o=wide -l'
  alias kcgdepwslowidel='kubectl_alias get deployment --watch --show-labels -o=wide -l'
  alias kcsysgdepwslowidel='kubectl_alias --namespace=kube-system get deployment --watch --show-labels -o=wide -l'
  alias kcexn='kubectl_alias exec -i -t --namespace'
  alias kclon='kubectl_alias logs -f --namespace'
  alias kcgn='kubectl_alias get --namespace'
  alias kcdn='kubectl_alias describe --namespace'
  alias kcrmn='kubectl_alias delete --namespace'
  alias kcgpon='kubectl_alias get pods --namespace'
  alias kcdpon='kubectl_alias describe pods --namespace'
  alias kcrmpon='kubectl_alias delete pods --namespace'
  alias kcgdepn='kubectl_alias get deployment --namespace'
  alias kcddepn='kubectl_alias describe deployment --namespace'
  alias kcrmdepn='kubectl_alias delete deployment --namespace'
  alias kcgsvcn='kubectl_alias get service --namespace'
  alias kcdsvcn='kubectl_alias describe service --namespace'
  alias kcrmsvcn='kubectl_alias delete service --namespace'
  alias kcgingn='kubectl_alias get ingress --namespace'
  alias kcdingn='kubectl_alias describe ingress --namespace'
  alias kcrmingn='kubectl_alias delete ingress --namespace'
  alias kcgcmn='kubectl_alias get configmap --namespace'
  alias kcdcmn='kubectl_alias describe configmap --namespace'
  alias kcrmcmn='kubectl_alias delete configmap --namespace'
  alias kcgsecn='kubectl_alias get secret --namespace'
  alias kcdsecn='kubectl_alias describe secret --namespace'
  alias kcrmsecn='kubectl_alias delete secret --namespace'
  alias kcgoyamln='kubectl_alias get -o=yaml --namespace'
  alias kcgpooyamln='kubectl_alias get pods -o=yaml --namespace'
  alias kcgdepoyamln='kubectl_alias get deployment -o=yaml --namespace'
  alias kcgsvcoyamln='kubectl_alias get service -o=yaml --namespace'
  alias kcgingoyamln='kubectl_alias get ingress -o=yaml --namespace'
  alias kcgcmoyamln='kubectl_alias get configmap -o=yaml --namespace'
  alias kcgsecoyamln='kubectl_alias get secret -o=yaml --namespace'
  alias kcgowiden='kubectl_alias get -o=wide --namespace'
  alias kcgpoowiden='kubectl_alias get pods -o=wide --namespace'
  alias kcgdepowiden='kubectl_alias get deployment -o=wide --namespace'
  alias kcgsvcowiden='kubectl_alias get service -o=wide --namespace'
  alias kcgingowiden='kubectl_alias get ingress -o=wide --namespace'
  alias kcgcmowiden='kubectl_alias get configmap -o=wide --namespace'
  alias kcgsecowiden='kubectl_alias get secret -o=wide --namespace'
  alias kcgojsonn='kubectl_alias get -o=json --namespace'
  alias kcgpoojsonn='kubectl_alias get pods -o=json --namespace'
  alias kcgdepojsonn='kubectl_alias get deployment -o=json --namespace'
  alias kcgsvcojsonn='kubectl_alias get service -o=json --namespace'
  alias kcgingojsonn='kubectl_alias get ingress -o=json --namespace'
  alias kcgcmojsonn='kubectl_alias get configmap -o=json --namespace'
  alias kcgsecojsonn='kubectl_alias get secret -o=json --namespace'
  alias kcgsln='kubectl_alias get --show-labels --namespace'
  alias kcgposln='kubectl_alias get pods --show-labels --namespace'
  alias kcgdepsln='kubectl_alias get deployment --show-labels --namespace'
  alias kcgwn='kubectl_alias get --watch --namespace'
  alias kcgpown='kubectl_alias get pods --watch --namespace'
  alias kcgdepwn='kubectl_alias get deployment --watch --namespace'
  alias kcgsvcwn='kubectl_alias get service --watch --namespace'
  alias kcgingwn='kubectl_alias get ingress --watch --namespace'
  alias kcgcmwn='kubectl_alias get configmap --watch --namespace'
  alias kcgsecwn='kubectl_alias get secret --watch --namespace'
  alias kcgwoyamln='kubectl_alias get --watch -o=yaml --namespace'
  alias kcgpowoyamln='kubectl_alias get pods --watch -o=yaml --namespace'
  alias kcgdepwoyamln='kubectl_alias get deployment --watch -o=yaml --namespace'
  alias kcgsvcwoyamln='kubectl_alias get service --watch -o=yaml --namespace'
  alias kcgingwoyamln='kubectl_alias get ingress --watch -o=yaml --namespace'
  alias kcgcmwoyamln='kubectl_alias get configmap --watch -o=yaml --namespace'
  alias kcgsecwoyamln='kubectl_alias get secret --watch -o=yaml --namespace'
  alias kcgowidesln='kubectl_alias get -o=wide --show-labels --namespace'
  alias kcgpoowidesln='kubectl_alias get pods -o=wide --show-labels --namespace'
  alias kcgdepowidesln='kubectl_alias get deployment -o=wide --show-labels --namespace'
  alias kcgslowiden='kubectl_alias get --show-labels -o=wide --namespace'
  alias kcgposlowiden='kubectl_alias get pods --show-labels -o=wide --namespace'
  alias kcgdepslowiden='kubectl_alias get deployment --show-labels -o=wide --namespace'
  alias kcgwowiden='kubectl_alias get --watch -o=wide --namespace'
  alias kcgpowowiden='kubectl_alias get pods --watch -o=wide --namespace'
  alias kcgdepwowiden='kubectl_alias get deployment --watch -o=wide --namespace'
  alias kcgsvcwowiden='kubectl_alias get service --watch -o=wide --namespace'
  alias kcgingwowiden='kubectl_alias get ingress --watch -o=wide --namespace'
  alias kcgcmwowiden='kubectl_alias get configmap --watch -o=wide --namespace'
  alias kcgsecwowiden='kubectl_alias get secret --watch -o=wide --namespace'
  alias kcgwojsonn='kubectl_alias get --watch -o=json --namespace'
  alias kcgpowojsonn='kubectl_alias get pods --watch -o=json --namespace'
  alias kcgdepwojsonn='kubectl_alias get deployment --watch -o=json --namespace'
  alias kcgsvcwojsonn='kubectl_alias get service --watch -o=json --namespace'
  alias kcgingwojsonn='kubectl_alias get ingress --watch -o=json --namespace'
  alias kcgcmwojsonn='kubectl_alias get configmap --watch -o=json --namespace'
  alias kcgsecwojsonn='kubectl_alias get secret --watch -o=json --namespace'
  alias kcgslwn='kubectl_alias get --show-labels --watch --namespace'
  alias kcgposlwn='kubectl_alias get pods --show-labels --watch --namespace'
  alias kcgdepslwn='kubectl_alias get deployment --show-labels --watch --namespace'
  alias kcgwsln='kubectl_alias get --watch --show-labels --namespace'
  alias kcgpowsln='kubectl_alias get pods --watch --show-labels --namespace'
  alias kcgdepwsln='kubectl_alias get deployment --watch --show-labels --namespace'
  alias kcgslwowiden='kubectl_alias get --show-labels --watch -o=wide --namespace'
  alias kcgposlwowiden='kubectl_alias get pods --show-labels --watch -o=wide --namespace'
  alias kcgdepslwowiden='kubectl_alias get deployment --show-labels --watch -o=wide --namespace'
  alias kcgwowidesln='kubectl_alias get --watch -o=wide --show-labels --namespace'
  alias kcgpowowidesln='kubectl_alias get pods --watch -o=wide --show-labels --namespace'
  alias kcgdepwowidesln='kubectl_alias get deployment --watch -o=wide --show-labels --namespace'
  alias kcgwslowiden='kubectl_alias get --watch --show-labels -o=wide --namespace'
  alias kcgpowslowiden='kubectl_alias get pods --watch --show-labels -o=wide --namespace'
  alias kcgdepwslowiden='kubectl_alias get deployment --watch --show-labels -o=wide --namespace'
fi
